apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u8r3xrlfi-go
  janus-idp.io/tekton: u8r3xrlfi-go
  backstage.io/kubernetes-id: u8r3xrlfi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8r3xrlfi-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
